### ISSUE TITLE
BuffLib breaks Omen functionality

### ISSUE THREAD

**Issue by fatlus** [Schaka/BuffLib#2]
The person who use BuffLib isn't visible in Omen. As you commented in the ElvUI git (https://github.com/ElvUI-TBC/ElvUI/issues/180), a fix would be awesome.

**Comment by Schaka** [comment]
BuffLib isn't meantto be used in PvE.
If you want to use it that way, you can delete all Ace3 dependencies from BuffLib and/or delete the "menu creation" BuffLib uses (bottom of the main Lua file).

I will not do this, because it requires debugging library incompatibilities for a use case BuffLib was never intended for. You can use DiamondThreatMeter instead if you have to.

**Comment by Tremolo4** [comment]
The problem is that BuffLib sends a lot of messages to every group/raid member but does not use ChatThrottleLib. That means everything that does use ChatThrottleLib gets congested because BuffLib constantly sends over the limit.

I don't think the limit applies on most private servers but it's still a good idea I guess.

**Comment by Schaka** [comment]
Thanks for the info! I do stand by my original answer regarding PvE usage. However, I also don't really see a solution for this problem. The second I throttle messages, timers will be off (they currently already are, due to latency). GetTime() is different on any computer, so it can't be used to sync timestamps.

**Comment by ehmetti** [comment]
> BuffLib isn't meantto be used in PvE.

> use case BuffLib was never intended for.

> I do stand by my original answer regarding PvE usage.

If the problem is caused by sync and this addon isn't meant to be used in PvE, the issue should be trivial to solve:

```lua
function BuffLib:SendSync(message)
	local inInstance, instanceType = IsInInstance()
	if instanceType == "pvp" then
		SendAddonMessage("BuffLib", message, "BATTLEGROUND")
	elseif instanceType == "raid" then
		SendAddonMessage("BuffLib", message, "RAID")
	elseif instanceType == "arena" or instanceType == "party" then
		SendAddonMessage("BuffLib", message, "PARTY")
```

-->

```lua
function BuffLib:SendSync(message)
	local inInstance, instanceType = IsInInstance()
	if instanceType == "pvp" then
		SendAddonMessage("BuffLib", message, "BATTLEGROUND")
	elseif instanceType == "arena" then
		SendAddonMessage("BuffLib", message, "PARTY")
```

Problem solved. No more PvE use. Although that's kind of a lazy approach, could just disable the event handlers altogether.

If you break other gameplay-critical addons, you at the very least need to detect the most common of them and prompt the user about compatibility issues with instructions how to resolve them. Switching your addon on an off depending on environment isn't a good solution, but it's a solution. Skipping sync (or disabling events) in raids is a better solution, and it's trivial.

Even better solution, retaining PvE functionality, would be to use some common sense on how to send syncs and self-throttle: For starters, don't send up to 80 messages for each potential (de)buff slot for all of the 3 targets every time there is a change. At the very least pool them up to a single message. If the message gets too long, keep record of previous state and transfer only the deltas (need to be careful with this one), or split it into a few parts. The sync logic, as it stands, is horrendously inefficient.

There are oh so many solutions to this problem. Every single one of them is miles better than wiping for multiple times over weeks for not having a functioning threat meter, wasting raid time having to debug this for hours, trying multiple versions of Omen, the list goes on. Multiply that by the number of users.

You can't seriously suggest that the users should just magically know to drop this addon while doing PvE? What kind of communication channels have you used to reach them? I'm sure all the third party legacy addon portals have been notified as well? And this being a lib, I'm sure you've made sure the same disclaimer is on every addon that uses this lib? No you haven't, and even if you had, it'd still be unneccessary and sloppy. Not good enough, bro. Fix your shit (or grant me push and I'll see if I can help if I find the time).

**Comment by Schaka** [comment]
I've never supported any PvE. I don't play PvE. I created all of these addons, before TBC PvE servers were even really a thing. I don't have any interest in supporting people who use PURELY PvP addons (like those showing enemy buff times) in a raid environment. And I definitely don't have any interest in supporting people who repost my stuff on their website for ad revenue. 

The only thing I agree with is that it shouldn't be called BuffLib. I originally intended for it to be a library but then figured it's easier to just hook functions instead of supplying my own and expecting people to download addons that utilize them. As it stands, only ArenaLive (couldn't be more clear about not being a PvE addon) uses BuffLib.

I know not throttling chat messages isn't efficient. But no server had bothered implementing anything along the lines of throttling before and our connections are generally good enough to handle that tiny bit of extra traffic. 

You know, you can always create a pull request, you don't need any permission. So if you care enough, create one - I'll test it briefly and merge it.

**Comment by Tremolo4** [comment]
> I know not throttling chat messages isn't efficient. But no server had bothered implementing anything along the lines of throttling before and our connections are generally good enough to handle that tiny bit of extra traffic.

Just to clarify, the problem occurs regardless of whether the server actually has a limit.
ChatThrottleLib (CTL) just assumes that there is a limit and prevents any addon, which throttles itself by using CTL (e.g., Omen), from sending messages if any other addon (with or without CTL, e.g., BuffLib) is currently exceeding this limit.
